# Site settings
title           : "I'm Glad You Asked"
email           : your-email@domain.com
description     : "This is the description."
baseurl         : "" # the subpath of your site, e.g. /blog
url             : "http://icsapo.github.io" # the base hostname & protocol for your site

# Author/contact
twitter_username: icsapo
github_username:  icsapo


# Pagination (http://jekyllrb.com/docs/pagination)
# - Add jekyll-paginate to gems.
paginate        : 5                     # max number of posts per page
#paginate_path   : "/page:num"           # after the first index.html pagination pages go
                                         # under this path (for example, page2/index.html)

# Permalinks (http://jekyllrb.com/docs/permalinks)
permalink       : /:year/:title

# Markdown
markdown        : kramdown

# Gems
gems            : [jekyll-paginate, jekyll-gist]

# Sass
# - The sass_dir variable defaults to _sass, so there is no need to define it here.
